name: Change module version

on:
  push:
    branches:
      - main

jobs:
  change_module_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed directories
        id: get-changes
        run: |

          changed_dirs=$(git diff --name-only origin/main...HEAD | grep '/' | cut -d'/' -f1 | sort -u)

          echo "in"
          for dir in $changed_dirs; do
            echo "Changed directory $dir"
            # Add your logic here to perform actions on each changed directory
          done


        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}