name: Change module version

on:
  push:
    branches:
      - main

jobs:
  change_module_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed directories
        id: get-changes
        run: |

          if [ -n "${{ github.event.before }}" ]; then
            before_commit=${{ github.event.before }}
          else
            # Use the initial commit for non-empty repositories
            before_commit=$(git rev-list --max-parents=0 HEAD)
          fi
          
          after_commit=${{ github.sha }}
          changed_dirs=$(git diff --name-only $before_commit $after_commit | grep '^.*\/' | sed 's/\/$//')
          echo "in"
          for dir in $changed_dirs; do
            echo "Changed directory $dir"
            # Add your logic here to perform actions on each changed directory
          done


        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}