name: Change module version

on:
  push:
    branches:
      - main

jobs:
  change_module_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: Get changed directories
        id: get-changes
        run: |

          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          
          changed_directories=()
          for file in ${changed_files[@]}; do
            echo "$file"
            if [[ "${file}" == .* ]]; then
              echo "skip"
              continue
            fi

            if [[ "${value}" == *"/"* ]]; then
              # Split value by /
              IFS='/' read -ra parts <<< "$file"

              # Get the first component as modified value
              directory_name="${parts[0]}"
            else
              echo "skip"
              continue
            fi
            
            echo "$directory_name"
            # Check if the modified value is not already in the list
            if [[ ! " ${changed_directories[@]} " =~ " ${directory_name} " ]]; then
                # Add the modified value to the list
                changed_directories+=("${directory_name}")
            fi

          done
          echo "Modified and Unique Values ${changed_directories[@]}"

          # Find all first level folders in repository 
          all_directories=$(find . -maxdepth 1 -type d -not -name ".*")
          for dir in ${changed_directories[@]}; do
            # Check if the folder has a file named __manifest__.py at depth 1
            if [[ -f "${dir}/__manifest__.py" ]]; then
                echo "${dir}"
                # You can add more logic here based on your requirements
            else
                echo "skip module $dir"
                continue
            fi
          done


        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}