name: Change module version

on:
  push:
    branches:
      - main

jobs:
  change_module_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Git Config
      run: |
      
        # Setup the username and email.
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
          
    - name: Change Module Version
      run: |
      
        # Find all first level folders in repository 
        directories_to_modify=$(find . -maxdepth 1 -type d -not -name ".*")
        for dir in $directories_to_modify; do
            cd "${dir:2}"
              if git diff --exit-code "$before_sha"; then
                echo "No differences found in ${dir:2} since the last commit."
              else
                # Print the differences
                git diff "$before_sha"
              fi
            # Return to the original directory
            cd ..
        done

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}