name: Change module version

on:
  push:
    branches:
      - main

jobs:
  change_module_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Git Config
      run: |
      
        # Setup the username and email.
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
          
    - name: Change Module Version
      run: |
      
        # Find all Python files with the .py extension 
        directories_to_modify=$(find . -maxdepth 2 -type d)
        for dir in $directories_to_modify; do
            echo "No changes in $dir. Nothing to commit."
        done

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}